name: Bug Report
description: Submit a bug report to help improve ai-dynamo
title: "[BUG]: <Enter bug title>"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report to improve ai-dynamo!

  - type: textarea
    id: bug-description
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide details about your environment.
      placeholder: |
        Operating System (Required): e.g. Ubuntu 24.04
        ai-dynamo Version (Required): e.g. 0.1.0 or git commit SHA if you cloned the repo
        ai-dynamo-runtime Version (Required): e.g. 0.1.0
        ai-dynamo-vllm Version (Required): e.g. 0.7.2
        nixl Version (Required): e.g. 0.1.0 or git commit SHA if you cloned the repo
        CPU Architecture (Required): e.g. x86_64 (run `uname -m`)
        CUDA Version (Required): e.g. 12.8 (run `nvidia-smi`)
        GPU Architecture (Required): e.g. A100 (run `nvidia-smi -L`)
        Python Version (Required): e.g. 3.12.3 (run `python --version`)
        glibc Version (Optional): e.g. 2.39 (run `ldd --version`)
        Docker Version (Optional): e.g. 28.0.2 (run `docker --version`)
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false
