VERSION 0.8


build:
    FROM golang:1.23
    ARG TARGETOS
    ARG TARGETARCH
    WORKDIR /
    COPY ../../../+operator-src/operator ./operator
    WORKDIR /workspace
    COPY go.mod go.mod
    COPY go.sum go.sum
    RUN go mod download
    COPY api/ api/
    COPY .env .env
    RUN CGO_ENABLED=0 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH} go build -a -o server api/main.go
    SAVE ARTIFACT /workspace/server
    SAVE ARTIFACT /workspace/.env

test:
    FROM +build
    COPY tests/ tests/
    WITH DOCKER
        RUN --privileged go test ./...
    END

docker:
    ARG CI_REGISTRY_IMAGE=my-registry
    ARG CI_COMMIT_SHA=latest
    ARG IMAGE=dynamo-api-server
    FROM python:3.9-slim
    WORKDIR /
    COPY +build/server .
    COPY +build/.env .
    COPY db/ db/
    RUN pip install -r db/requirements.txt
    ENV PYTHONPATH="/:${PYTHONPATH}"
    USER 65532:65532
    ENTRYPOINT ["/server"]
    SAVE IMAGE --push $CI_REGISTRY_IMAGE/$IMAGE:$CI_COMMIT_SHA