# SPDX-FileCopyrightText: Copyright (c) 2024-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

VERSION 0.8

# Base container for both build and test
deps:
    FROM ../../../+golang-base
    COPY . /app/operator
    WORKDIR /app/operator
    RUN go mod download

lint:
    FROM +deps
    RUN golangci-lint run --config ./.golangci.yml

build:
    FROM +deps
    RUN CGO_ENABLED=0 go build -o manager ./cmd/main.go
    SAVE ARTIFACT manager

test:
    FROM +deps
    RUN make test
    SAVE ARTIFACT cover.out

docker:
    ARG CI_REGISTRY_IMAGE=my-registry
    ARG CI_COMMIT_SHA=latest
    ARG IMAGE_SUFFIX=dynamo-operator
    FROM gcr.io/distroless/static-debian11
    WORKDIR /
    COPY +build/manager .
    USER 65532:65532
    CMD ["./manager"]
    SAVE IMAGE --push $CI_REGISTRY_IMAGE/$IMAGE_SUFFIX:$CI_COMMIT_SHA
